### ISSUE TITLE
`hono` is not declared as peer dependency

### ISSUE THREAD

**Issue by marvinruder** [honojs/node-server#191]
Given a Hono project under Node.js using the Yarn package manager with Yarn PnP enabled, when attempting to import `@hono/node-server`, then the import fails with the message

```
  The Yarn Plug'n'Play manifest forbids importing "hono" here because it's not listed as a
  dependency of this package:
```

This is because `@hono/node-server` uses imports from `hono` (e.g. [here](https://github.com/honojs/node-server/blob/e42500f07d1eaff989cb63710afb8737f7b3c055/src/serve-static.ts#L4)) without declaring it as either a dependency or a peer dependency.

A possible workaround at the moment is to set

```yaml
packageExtensions: 
  "@hono/node-server@*": 
    peerDependencies: 
      "hono": "*"
```

in your `.yarnrc.yml`
